site_name: Serendipity - Dev. Guidelines

theme:
  name: material
  features:
    - instant.loading
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
  - awesome-pages

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - attr_list
  - md_in_html

extra_css:
  - assets/css/custom.css

nav:
  - Home:
      - Start here: index.md
      - Starting new projects:
          - New project Kit: new_project_kit/discovery_and_ideation_worksheet_template/
  - New Project Kit:
      - Start here: new_project_kit/project_setup_guide.md
      - Repo Templates List:
          - Templates Repos: new_project_kit/templates_repos.md
          - WebApp Template: new_project_kit/webapp_template.md
          - Admin Panel Template: new_project_kit/admin_panel_template.md
          - Mobile App Template: new_project_kit/mobile_app_template.md
          - Backend Template: new_project_kit/backend_template.md
      - Product Requirements Document (PRD):
          - Discovery and Ideation — Worksheet: new_project_kit/discovery_and_ideation_worksheet_template.md
          - PRD Template: new_project_kit/prd_template.md
      - Technical Design Documentation:
          - TDD Template: new_project_kit/tdd_template.md
          - TDD Template (with examples): new_project_kit/tdd_template_with_examples.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SerendipityOrg/TradeMan-Dev-Guidelines
